### ISSUE TITLE
Make disabling redirects opt-in

### ISSUE THREAD

**Issue by mbrodala** [networkteam/redirects_healthcheck#1]
The CLI command should by default only check the health of redirects and not directly disable broken redirects.

Aside from temporary network issues there could be various other reasons to not disable redirects right away.

Also being non-destructive by default is always a good thing. ;-)

So e.g. a `--disable-inactive` CLI option should be added.

**Comment by christophlehmann** [comment]
As a cli user i learned to never run an unknown cli command and the help text already mentioned it ;-) But yes, this option should definitely be realised.
