### ISSUE TITLE
Incorrect site "base" used for check

### ISSUE THREAD

**Issue by mbrodala** [networkteam/redirects_healthcheck#4]
Maybe fixable by #3 but should be mentioned nevertheless: right now an incorrect site "base" is used for the redirect health check.

It looks like the `base` of the first existing site is used instead of the `base` matching a given page redirect. Of course when using `baseVariants` one needs to take care of setting up the environment on CLI/Cron to have the correct variant resolved. But the check should still try to determine the correct site.

**Comment by christophlehmann** [comment]
I added an argument for the default site and mentioned it in the readme, so this is IMHO resolved.

**Comment by mbrodala** [comment]
Thanks! :-)

**Comment by mbrodala** [comment]
I just checked and unfortunately this doesn't work for domain redirects not covered by any site. It's perfectly valid to define arbitrary domain redirects and redirect them anywhere, there doesn't have to exist a site for such a domain. Currently I get a `No site found` exception, even with the `--siteIdentifier` (should be `--site-identifier` IMO) argument.
